### ISSUE TITLE
Demo not found!

### ISSUE THREAD

**Issue by cjnimes** [angular-ui/ui-uploader#12]
The demo has this url: http://realtica.org/ng-uploader/demo.html, but it doesn't exists

**Comment by PowerKiKi** [comment]
@realtica would you be able to restore the demo page ? or should we look for another solution ?

**Comment by shikshik** [comment]
+1

**Comment by PowerKiKi** [comment]
It would seems @realtica is not active on GitHub for the last 10 months. So I guess we won't get the demo back up. Anyone know of a solution that could replace it ?

**Comment by clrech** [comment]
@PowerKiKi , replace the URL in https://github.com/angular-ui/ui-uploader/blob/master/demo/index.html#L30 with https://angular-file-upload-cors-srv.appspot.com/upload
It should work.

**Comment by PowerKiKi** [comment]
@clrech is this your server ?

**Comment by clrech** [comment]
@PowerKiKi sadly no, it's from another AngularJS uploader project, but I've found another server built for testing purposes: **https://posttestserver.com/post.php**
Take a look at https://www.posttestserver.com
