### ISSUE TITLE
TypeError: self.options.onCompletedAll is not a function

### ISSUE THREAD

**Issue by jlav1n** [angular-ui/ui-uploader#2]
Seen upon performing upload in the JS console. If the official demo was up, you would see it there, but it's down...

I hacked together this demo (open your console window before trying):
https://jsbin.com/zawiricepi/edit?html,js,output

**Comment by PowerKiKi** [comment]
Please submit a PR to fix it. Adding a `if` somewhere should probably be enough

**Comment by jlav1n** [comment]
Sure, but I don't understand the reason for onCompletedAll... Is there a test that is breaking by it's failure to work?

**Comment by PowerKiKi** [comment]
See the recent addition in https://github.com/angular-ui/ui-uploader/commit/7fe8c28

**Comment by PowerKiKi** [comment]
This actually has been fixed a while ago in bd8b0a741781a12c4ee1a7e40e59b7e3e9ebe74b
