### ISSUE TITLE
uiUploader config - URL?

### ISSUE THREAD

**Issue by francisalfanta** [angular-ui/ui-uploader#21]
In your Configure ui-uploader callbacks, you have URL option.

What's the URL file expected function should be doing and data structure?

I am using API .Net and AngularJS. I can not figure out what API call should i use.

**Comment by PowerKiKi** [comment]
As you can see [from the code](https://github.com/angular-ui/ui-uploader/blob/master/src/uploader.js#L115-L129) I don't think there is any required format for the response from the server. If you use the `onCompleted` callback, then you should return whatever you will need in your `onCompleted` implementation.

**Comment by PowerKiKi** [comment]
Just updated [the demo](https://htmlpreview.github.io/?https://github.com/angular-ui/ui-uploader/master/demo/index.html) where you can see that indeed the server's response does not matter to ui-uploader.
