### ISSUE TITLE
Setting key in ajaxUpload

### ISSUE THREAD

**Issue by dardub** [angular-ui/ui-uploader#4]
On line 68 I see:

``` javascript
var xhr, formData, prop, key = '' || 'file';
```

What is the point of '' || 'file'

Doesn't it always evaluate to 'file'?

**Comment by PowerKiKi** [comment]
Indeed that seems suspicious ... did you try blaming the file to see who wrote that when ? I guess you'd have to go back quite far in time...

**Comment by PowerKiKi** [comment]
Faster than I thought, it seems it appearead in the very first commit of the original project: https://github.com/realtica/ng-uploader/commit/1c9e84dad4f33476030431fdc3a5d18dafbac2ce#diff-fccb9ea6ccaa1552e74050d47a748ee8R80

I'd say it's indeed a mistake and should be removed in a PR

**Comment by ggwp0101** [comment]
Hi PowerKiKi. It would be great to see this fix in release version. With abiltity to change the key. Thanks

**Comment by PowerKiKi** [comment]
@AleksejDomash submit a PR and it will be merged
